# Setup
title:               Milan 1958-1962
tagline:             'Music Topography of a City'
description:         'Prototype website for PhD project "Milan 1958-1962: Music Topography of a City" by Martin Nicastro'
url:                 "https://www.musictopography.com"
baseurl:             ''
paginate:            4
permalink:           pretty

# About/contact
author:
  name:              Martin Nicastro
  url:               https://www.martinnicastro.com/
  email:             nicastromartin@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
